### ISSUE TITLE
Enable accessing the user's ORCID to the authors

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#754] opened 2023-01-21 19:13 UTC
The user profile ORCID should be accessible by other parts of nmrXiv

**Comment by NRayya** [comment] 2023-01-21 19:13
Related to #728 to https://github.com/NFDI4Chem/nmrxiv/issues/472

**Comment by NishaSharma14** [comment] 2023-02-22 12:24
Duplicate of #729

**Closed by NishaSharma14** 2023-02-22 12:24 UTC
Labels: duplicate, feature
