### ISSUE TITLE
jcamp file not recognized but jdx file is recognized

### ISSUE THREAD

**Issue by tditfe** [NFDI4Chem/nmrxiv#645] opened 2022-11-30 12:13 UTC
**Describe the bug**
The upload of the same datafile with different extension does not work. The same Data file was used for individual upload. Once named as with the file extension XXX.jdx and once named as XXX.jcamp. After the upload the XXX.jdx will be recognized and the XXX.jcamp is not recognized.

**To Reproduce**
1. Click upload
2. Enter project name and project description
3. Upload the file XXX.jcamp as Study
4. The file is not recoginzed as Study (bug) and cant be used in the next step 

-----for confirmation-----
1. Rename XXX.jcamp to XXX.jdx
2. Click upload
3. Enter project name and project description
6. Upload the XXX.jdx as Study
7. The renamed file is now visable/recognized as Study and can be used in the next step 

**Expected behavior**

The XXX.jcamp file should also be usable. The file extentsion should not hinder the Software to recognize the file as suitable.

**Screenshots**

![Screenshot (18)](https://user-images.githubusercontent.com/116734554/204775904-dd840063-75d1-46ea-96d7-f66ee6ef55af.png)

![Screenshot (20)](https://user-images.githubusercontent.com/116734554/204775924-854c86ca-3bf9-48e5-8339-3dd0615e7c13.png)

**Desktop**
 - Win 10 Pro Version 21H2
 - Firefox 107.0 (32-bit)

**Additional context**
Used Dataset:
https://knowledgebase.nfdi4chem.de/knowledge_base/docs/lead-by-example/?text=10.1039/D2SC02910C

Chemotion entry of a usable data for reproduction
https://dx.doi.org/10.14272/reaction/SA-FUHFF-UHFFFADPSC-JHIAOWGCGN-UHFFFADPSC-NUHFF-NUHFF-NUHFF-ZZZ

**Comment by NRayya** [comment] 2022-12-07 15:31
Good evening @tditfe 
This is actually an NMRium thing. Could you please open an issue there? 
https://github.com/cheminfo/nmrium

**Comment by NRayya** [comment] 2022-12-25 23:51
@tditfe The problem is fixed in NMRium and will be fixed in nmrXiv when we upgrade our NMRium version soon

**Closed** 2023-11-13 11:55 UTC
Labels: bug
