### ISSUE TITLE
Spectrum with ID not found error 

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#1094] opened 2024-02-28 13:57 UTC
chlorhexan_544-10-5 dataset is failing to load on nmrxiv

**Comment by CS76** [comment] 2024-02-28 13:58
@jliermann to provide spectra files

**Comment by jliermann** [comment] 2024-02-28 17:03
Dataset is larger than 25MB so I share it here:
https://seafile.rlp.net/d/2929a00c77d3428cb669/

Link expires in 60 days.

**Comment by NishaSharma14** [comment] 2024-03-01 10:45
<img width="1613" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/54287612/83044f01-ffd4-4b99-8f9d-ff042ca89da8">

[nmriuminfo.json](https://github.com/NFDI4Chem/nmrxiv/files/14459960/nmriuminfo.json)

**Comment by hamed-musallam** [comment] 2024-03-05 11:26
It appears that the issue stems from NMRium, the auto-processing did not function as intended, resulting in this problem. We will resolve this issue soon. I need to discuss with the team whether the auto-processing for the NMRium object should be done in the wrapper or We should wait until it is resolved in the NMRium itself.

**Comment by hamed-musallam** [comment] 2024-03-05 11:52
@CS76 

it is weird for me !!!,  How did you generate the NMRium object initially? It should include filters, and they should be saved in the backend.

**Comment by hamed-musallam** [comment] 2024-03-05 12:00
> It appears that the issue from NMRium, the auto-processing did not function as intended, resulting in this problem. We will resolve this issue soon. I need to discuss with the team whether the auto-processing for the NMRium object should be done in the wrapper or We should wait until it is resolved in the NMRium itself.

@CS76 

It appears that we didn't implement auto-processing on the NMRium object for a specific reason. The NMRium object should already contain those filters, and NMRium should accept the object as it is without further action, except for migration. It should be saved in the backend. Could you give me a hand in debugging the issue and determine why you're not receiving the filters?

**Comment by NishaSharma14** [comment] 2024-03-06 15:13
@hamed-musallam as @CS76 is on leave, I can try to help you in debugging this and provide the details.

**Comment by NishaSharma14** [comment] 2024-03-07 14:54
@jliermann This issue is resolved. Please try once again and check if the NMRium loads for you. If not then you will have to have to delete the files and re-upload them once again. Kindly reach out to us if it doesn't work.

Thanks @hamed-musallam for your help.

[screen-capture (32).webm](https://github.com/NFDI4Chem/nmrxiv/assets/54287612/56a773ed-41cc-4d72-910b-20cceb416107)

**Comment by jliermann** [comment] 2024-03-08 15:03
@NishaSharma14 @hamed-musallam 
Thanks, it seems to work now!

**Closed** 2024-03-13 08:57 UTC
Labels: bug, testing
